config:
  credentials: []
  project_repos:
    github.com/ARGOeu/argo-messaging:
      branch: master
      repo: https://github.com/ARGOeu/argo-messaging
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ARGOeu/argo-messaging git:
        commands:
        - /usr/bin/env sh .sqa/script.ready-copper-budgerigar.sh
        container: qc.acc_cheeky-aqua-weasel
  QC.Doc:
    repos:
      github.com/ARGOeu/argo-messaging find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-sapphire-lynx.sh
        container: qc.doc_homely-blue-antelope
      github.com/ARGOeu/argo-messaging git:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-firebrick-terrier.sh
        container: qc.doc_dorky-lilac-markhor
      github.com/ARGOeu/argo-messaging markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-jade-starfish.sh
        container: qc.doc_ugly-puce-quoll
  QC.Lic:
    repos:
      github.com/ARGOeu/argo-messaging licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-wisteria-javanese.sh
        container: qc.lic_breezy-xanthic-dragon
  QC.Met:
    repos:
      github.com/ARGOeu/argo-messaging cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.homey-corn-drever.sh
        container: qc.met_snazzy-periwinkle-bonobo
      github.com/ARGOeu/argo-messaging validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-teal-llama.sh
        container: qc.met_dorky-rose-opossum
  QC.Sec:
    repos:
      github.com/ARGOeu/argo-messaging bandit:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-denim-moose.sh
        container: qc.sec_woolly-black-spaniel
      github.com/ARGOeu/argo-messaging gosec:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-asparagus-sheepdog.sh
        container: qc.sec_skimpy-copper-toucan
  QC.Sty:
    repos:
      github.com/ARGOeu/argo-messaging flake8:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-ivory-dhole.sh
        container: qc.sty_paltry-brass-whippet
      github.com/ARGOeu/argo-messaging jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-maroon-butterfly.sh
        container: qc.sty_beady-sangria-koala
      github.com/ARGOeu/argo-messaging staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-amethyst-dunker.sh
        container: qc.sty_thirsty-mustard-buzzard
  QC.Uni:
    repos:
      github.com/ARGOeu/argo-messaging pytest:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-saffron-frise.sh
        container: qc.uni_shaggy-purple-quetzal
  QC.Ver:
    repos:
      github.com/ARGOeu/argo-messaging get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-khaki-weasel.sh
        container: qc.ver_snappy-zucchini-gar
timeout: 5400
