config:
  credentials: []
  project_repos:
    github.com/ARGOeu/argo-messaging:
      branch: master
      repo: https://github.com/ARGOeu/argo-messaging
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: fix/updatego
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ARGOeu/argo-messaging git:
        commands:
        - /usr/bin/env sh .sqa/script.marigold_reflective_finch.sh
        container: qc.acc_viridian_wise_dhole
  QC.Doc:
    repos:
      github.com/ARGOeu/argo-messaging find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sienna_mysterious_boa.sh
        container: qc.doc_polar_productive_warthog
      github.com/ARGOeu/argo-messaging git:
        commands:
        - /usr/bin/env sh .sqa/script.lilac_motivated_kingfisher.sh
        container: qc.doc_coffee_humorous_boa
      github.com/ARGOeu/argo-messaging markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.wheat_attentive_parrot.sh
        container: qc.doc_red_optimistic_gibbon
  QC.Lic:
    repos:
      github.com/ARGOeu/argo-messaging licensee:
        commands:
        - /usr/bin/env sh .sqa/script.clove_helpful_goose.sh
        container: qc.lic_iris_scrappy_emu
  QC.Met:
    repos:
      github.com/ARGOeu/argo-messaging cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.yellow_restless_gibbon.sh
        container: qc.met_fog_graceful_horse
      github.com/ARGOeu/argo-messaging validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.persimmon_persistent_porcupine.sh
        container: qc.met_dusk_affectionate_owl
  QC.Sec:
    repos:
      github.com/ARGOeu/argo-messaging bandit:
        commands:
        - /usr/bin/env sh .sqa/script.viridian_proud_rhinoceros.sh
        container: qc.sec_caramel_tactful_skunk
      github.com/ARGOeu/argo-messaging gosec:
        commands:
        - /usr/bin/env sh .sqa/script.fog_sarcastic_squid.sh
        container: qc.sec_cherry_apathetic_elk
  QC.Sty:
    repos:
      github.com/ARGOeu/argo-messaging flake8:
        commands:
        - /usr/bin/env sh .sqa/script.obsidian_spirited_osprey.sh
        container: qc.sty_cosmos_creative_whale
      github.com/ARGOeu/argo-messaging jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.white_jubilant_ferret.sh
        container: qc.sty_sand_elated_donkey
      github.com/ARGOeu/argo-messaging staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.slate_witty_peacock.sh
        container: qc.sty_ice_amused_gazelle
  QC.Uni:
    repos:
      github.com/ARGOeu/argo-messaging pytest:
        commands:
        - /usr/bin/env sh .sqa/script.byzantium_carefree_wildcat.sh
        container: qc.uni_arctic_savvy_nymph
  QC.Ver:
    repos:
      github.com/ARGOeu/argo-messaging get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.tangerine_reserved_gazelle.sh
        container: qc.ver_brown_eccentric_cockatoo
timeout: 5400
