config:
  credentials: []
  project_repos:
    github.com/ARGOeu/argo-messaging:
      branch: devel
      repo: https://github.com/ARGOeu/argo-messaging
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ARGOeu/argo-messaging git:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-amber-tortoise.sh
        container: qc.acc_smelly-charcoal-discus
  QC.Doc:
    repos:
      github.com/ARGOeu/argo-messaging find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.surly-ochre-yak.sh
        container: qc.doc_pokey-purple-bat
      github.com/ARGOeu/argo-messaging git:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-zucchini-yak.sh
        container: qc.doc_skanky-champagne-zonkey
      github.com/ARGOeu/argo-messaging markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-vermilion-wasp.sh
        container: qc.doc_scummy-dandelion-collie
  QC.Lic:
    repos:
      github.com/ARGOeu/argo-messaging licensee:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-sepia-greyhound.sh
        container: qc.lic_squeaky-grey-dane
  QC.Met:
    repos:
      github.com/ARGOeu/argo-messaging cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-linen-stingray.sh
        container: qc.met_sloppy-magnolia-audemer
      github.com/ARGOeu/argo-messaging validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-beige-slug.sh
        container: qc.met_cozy-ochre-manatee
  QC.Sec:
    repos:
      github.com/ARGOeu/argo-messaging bandit:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-olive-setter.sh
        container: qc.sec_messy-xanthic-ray
      github.com/ARGOeu/argo-messaging gosec:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-cinnamon-caterpillar.sh
        container: qc.sec_slimy-copper-dingo
  QC.Sty:
    repos:
      github.com/ARGOeu/argo-messaging flake8:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-grey-mau.sh
        container: qc.sty_skinny-violet-rattlesnake
      github.com/ARGOeu/argo-messaging jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-denim-dingo.sh
        container: qc.sty_skimpy-wisteria-badger
      github.com/ARGOeu/argo-messaging staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-jade-mist.sh
        container: qc.sty_sleazy-ivory-sloth
  QC.Uni:
    repos:
      github.com/ARGOeu/argo-messaging pytest:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-cerulean-coati.sh
        container: qc.uni_flabby-celadon-hedgehog
  QC.Ver:
    repos:
      github.com/ARGOeu/argo-messaging get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-saffron-axolotl.sh
        container: qc.ver_ugly-black-centipede
timeout: 5400
