config:
  credentials: []
  project_repos:
    github.com/ARGOeu/argo-messaging:
      branch: devel
      repo: https://github.com/ARGOeu/argo-messaging
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ARGOeu/argo-messaging git:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-blue-lemming.sh
        container: qc.acc_leaky-linen-birman
  QC.Doc:
    repos:
      github.com/ARGOeu/argo-messaging find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-vermilion-chinook.sh
        container: qc.doc_greasy-harlequin-cuscus
      github.com/ARGOeu/argo-messaging git:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-bronze-fossa.sh
        container: qc.doc_tasty-scarlet-coral
      github.com/ARGOeu/argo-messaging markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-fuchsia-malamute.sh
        container: qc.doc_grumpy-puce-slug
  QC.Lic:
    repos:
      github.com/ARGOeu/argo-messaging licensee:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-thistle-chameleon.sh
        container: qc.lic_messy-pumpkin-bison
  QC.Met:
    repos:
      github.com/ARGOeu/argo-messaging cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-cobalt-otter.sh
        container: qc.met_silly-gold-weasel
      github.com/ARGOeu/argo-messaging validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-wheat-gar.sh
        container: qc.met_stuffy-chocolate-affenpinscher
  QC.Sec:
    repos:
      github.com/ARGOeu/argo-messaging bandit:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-black-wombat.sh
        container: qc.sec_hazy-gamboge-fossa
      github.com/ARGOeu/argo-messaging gosec:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-jade-bloodhound.sh
        container: qc.sec_squirrely-scarlet-tapir
  QC.Sty:
    repos:
      github.com/ARGOeu/argo-messaging flake8:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-green-rat.sh
        container: qc.sty_flimsy-brown-otter
      github.com/ARGOeu/argo-messaging jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-taupe-warthog.sh
        container: qc.sty_greasy-magenta-spider
      github.com/ARGOeu/argo-messaging staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.beady-grey-insect.sh
        container: qc.sty_foggy-red-corgi
  QC.Uni:
    repos:
      github.com/ARGOeu/argo-messaging pytest:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-indigo-lionfish.sh
        container: qc.uni_thirsty-yellow-dugong
  QC.Ver:
    repos:
      github.com/ARGOeu/argo-messaging get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-magenta-wallaby.sh
        container: qc.ver_snoopy-alizarin-gopher
timeout: 5400
