config:
  credentials: []
  project_repos:
    github.com/ARGOeu/argo-messaging:
      branch: master
      repo: https://github.com/ARGOeu/argo-messaging
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ARGOeu/argo-messaging git:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-dandelion-barb.sh
        container: qc.acc_seedy-mauve-mongoose
  QC.Doc:
    repos:
      github.com/ARGOeu/argo-messaging find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-zucchini-raccoon.sh
        container: qc.doc_pasty-fuchsia-dunker
      github.com/ARGOeu/argo-messaging git:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-jade-cheetah.sh
        container: qc.doc_hilly-wisteria-loon
      github.com/ARGOeu/argo-messaging markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-asparagus-jaguar.sh
        container: qc.doc_stealthy-magenta-mandrill
  QC.Lic:
    repos:
      github.com/ARGOeu/argo-messaging licensee:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-bistre-dhole.sh
        container: qc.lic_stinky-platinum-coral
  QC.Met:
    repos:
      github.com/ARGOeu/argo-messaging cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-cinnabar-grouse.sh
        container: qc.met_squeaky-white-dhole
      github.com/ARGOeu/argo-messaging validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-apricot-ferret.sh
        container: qc.met_nerdy-mauve-sparrow
  QC.Sec:
    repos:
      github.com/ARGOeu/argo-messaging bandit:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-lime-swan.sh
        container: qc.sec_cloudy-asparagus-duck
      github.com/ARGOeu/argo-messaging gosec:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-goldenrod-armadillo.sh
        container: qc.sec_nerdy-corn-toad
  QC.Sty:
    repos:
      github.com/ARGOeu/argo-messaging flake8:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-chartreuse-moose.sh
        container: qc.sty_skimpy-khaki-bobcat
      github.com/ARGOeu/argo-messaging jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-jade-akbash.sh
        container: qc.sty_lanky-amethyst-mole
      github.com/ARGOeu/argo-messaging staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-pink-tortoise.sh
        container: qc.sty_hilly-bistre-butterfly
  QC.Uni:
    repos:
      github.com/ARGOeu/argo-messaging pytest:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-cobalt-dunker.sh
        container: qc.uni_zippy-crimson-pig
  QC.Ver:
    repos:
      github.com/ARGOeu/argo-messaging get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-taupe-nightingale.sh
        container: qc.ver_hasty-viridian-stingray
timeout: 5400
