services:
  qc.acc_viridian_wise_dhole:
    command: sleep 6000000
    image: bitnami/git:2.34.1
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
  qc.doc_coffee_humorous_boa:
    command: sleep 6000000
    image: bitnami/git:2.34.1
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
  qc.doc_polar_productive_warthog:
    build:
      context: ./github.com/EOSC-synergy/sqaaas-tooling/QC.Doc
      dockerfile: Dockerfile
    command: sleep 6000000
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
  qc.doc_red_optimistic_gibbon:
    build:
      context: ./github.com/EOSC-synergy/sqaaas-tooling/QC.Doc/markdownlint
      dockerfile: Dockerfile
    command: sleep 6000000
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
  qc.lic_iris_scrappy_emu:
    command: sleep 6000000
    image: eoscsynergy/sqaaas-licensee:9.17.0
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
  qc.met_dusk_affectionate_owl:
    command: sleep 6000000
    image: alpine:3.15.0
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
  qc.met_fog_graceful_horse:
    build:
      context: ./github.com/EOSC-synergy/sqaaas-tooling/QC.Met/cff-converter-python
      dockerfile: Dockerfile
    command: sleep 6000000
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
  qc.sec_caramel_tactful_skunk:
    build:
      context: ./github.com/EOSC-synergy/sqaaas-tooling/QC.Sec/bandit
      dockerfile: Dockerfile
    command: sleep 6000000
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
  qc.sec_cherry_apathetic_elk:
    build:
      context: ./github.com/EOSC-synergy/sqaaas-tooling/QC.Sec/gosec
      dockerfile: Dockerfile
    command: sleep 6000000
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
  qc.sty_cosmos_creative_whale:
    command: sleep 6000000
    image: pipelinecomponents/flake8:0.19.0
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
  qc.sty_ice_amused_gazelle:
    build:
      context: ./github.com/EOSC-synergy/sqaaas-tooling/QC.Sty/staticcheck
      dockerfile: Dockerfile
    command: sleep 6000000
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
  qc.sty_sand_elated_donkey:
    build:
      context: ./github.com/EOSC-synergy/sqaaas-tooling/QC.Sty/jsonlint
      dockerfile: Dockerfile
    command: sleep 6000000
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
  qc.uni_arctic_savvy_nymph:
    command: sleep 6000000
    image: eoscsynergy/sqaaas-pytest:7.1.3-alpha
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
  qc.ver_brown_eccentric_cockatoo:
    build:
      context: ./github.com/EOSC-synergy/sqaaas-tooling/QC.Ver
      dockerfile: Dockerfile
    command: sleep 6000000
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
version: '3.7'
